### ISSUE TITLE
:mortar_board: :telescope: Change `EmptyStackException` out for `NoSuchElementException` in for stacks

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#107]
### What 
Replace the use of `EmptyStackException` for `NoSuchElementException` in the stack interface, implementations, tests, and topic pages. 

### Why
Looks like `EmptyStackException` is ancient. I don't believe there is anything intrinsically wrong with using the `EmptyStackException`, but since there is no `EmptyQueueException`, I suggest being consistent with the exceptions thrown :lipstick:. It appears that the exception of choice would be `NoSuchElementException`.  

### Where
src/test/java/LinkedStackTest.java
src/test/java/ArrayStackTest.java
src/main/java/ArrayStack.java
src/main/java/LinkedStack.java
/src/site/topic6.rst
src/site/topic8.rst
src/site/topic8-nested.rst
src/site/topic9.rst

### How
* `EmptyStackException`  -> `NoSuchElementException`
* Watch for imports
* Watch for testing code examples catching the exception
* Also add a string to the exception saying what happened: _Popping from an empty stack._

### Additional Notes
Not needed, but would be good for consistency.

**Comment by twentylemon** [comment]
Could also create your own `EmptyQueueException`. `EmptyStackException` is indeed ancient, but still appropriate for a _stack_.

**Comment by jameshughes89** [comment]
Not a bad idea to make our own, and I do want to make our own exception, but I think I will save that for an assignment or something.
