### ISSUE TITLE
Put the code in a better directory

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#15]
Currently all the code is in the `code` folder. 

Either (a) make sub directories of `code/src/` and `code/tst` or (b) just rename `code` to `src` and add `tst`. 

Option (b) may be easier with how sphinx works.

**Comment by twentylemon** [comment]
Could also follow the [maven directory structure](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) or the [gradle one](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html). As far as I know, gradle is more popular than maven nowadays, so it's likely what the students would see once in the real world. TLDR is:

* `src/main/java` - java sources
* `src/test/java` - java tests
* `src/site` - site templates

Gradle or maven itself would be nice to have, but maybe later. Sphinx plugins exist for both for `site` generation. Build would also run all the java unit tests, etc. Would take some learning, but whatever you do could be applicable to other courses/projects as well.

**Comment by jameshughes89** [comment]
Reopened since there may still be future improvements about this.
