### ISSUE TITLE
:telescope: :mortar_board: Add bag idea to early topics

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#167]
### What 
Update topics to include reference to bags. This will require making the indexed and sorted lists bags, or at least calling them that. 

### Why
Lists were replaced with Bags, so bags should be discussed. 

### Where
I think this will come up only in the first few topics.

**Comment by twentylemon** [comment]
Not sure I agree. Lists are substantially more common than bags in the wild, and likely to be more familiar given their python backgrounds.
