### ISSUE TITLE
:mortar_board: :telescope: Change generic parameters

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#203]
### What 
Replace all the `T`s with `E`s in the generic collections. 

### Why
Could follow the convention mentioned [here](https://docs.oracle.com/javase/tutorial/java/generics/types.html):

> By convention, type parameter names are single, uppercase letters. This stands in sharp contrast to the variable naming conventions that you already know about, and with good reason: Without this convention, it would be difficult to tell the difference between a type variable and an ordinary class or interface name.
> 
> The most commonly used type parameter names are:
> 
> E - Element (used extensively by the Java Collections Framework)
> K - Key
> N - Number
> T - Type
> V - Value
> S,U,V etc. - 2nd, 3rd, 4th types
> 

### Where
Anywhere `T` is used, so both the topic pages and the code itself

### Additional Notes
Low priority.

**Comment by twentylemon** [comment]
`T` tends to be more typical than `E`, it comes from `T`emplate `T`ype in C. `K` and `V` I definitely see a lot of, but definitely more common is `T`, `U`, then `T1`, `T2`, etc. The _only_ places I've seen `E` are in the collections framework, and libraries extending it (such as [guava](https://guava.dev/releases/30.0-jre/api/docs/com/google/common/collect/ImmutableCollection.html)), though even newer additions like [Stream](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html) use `Stream<T>`.
