### ISSUE TITLE
🐛 Outline Spelling Error in "March"

### ISSUE THREAD

**Issue by FosShow** [jameshughes89/cs102#409]
### What 
A major spelling error on the website. It said Match for due date when it should be March. 🥇 

### Why
Maybe you didn't use Grammarly or the Oxford dictionary? (shoutout Grammarly for all my essays) 

### Where
Under Student Evaluation (Tentative Dates) in the Outline for Computer Science 162 — Programming and Data Structures 👍 

### How
Use the Oxford dictionary in the library? 📖 🦖 👨‍🏫

**Comment by twentylemon** [comment]
I really hope this is written with sarcasm.

**Comment by FosShow** [comment]
🤣

**Comment by twentylemon** [comment]
> 🤣

Ok, good. Add some emojis brother, they add a lot to tone. Otherwise you sound like a jerk (like this).

**Comment by FosShow** [comment]
got you

**Comment by twentylemon** [comment]
> Haha what an idiot, he thinks I'm an ass!

Checks out.

**Comment by FosShow** [comment]
hahahahahah

**Comment by jameshughes89** [comment]
@FosShow Maybe have at this one.
