### ISSUE TITLE
Consider grouping website topics into their own directories

### ISSUE THREAD

**Issue by twentylemon** [jameshughes89/cs102#46]
Currently, the website is laid out as:

* `src/site` -- root
  * `src/site/topicX.rst` -- lecture topic #X
  * `src/site/topicX-aside.rst` -- aside for topic #X
  * `src/site/img/Y.png` -- some image `Y.png`

Instead, maybe group related items together into subdirectories.

* `src/site` -- root
  * `src/site/topicX/index.rst` -- lecture topic #X
  * `src/site/topicX/img/Y.png` -- some image used in topic #X; `src/site/topicX/Y.png` would be fine too
  * `src/site/topicX/aside.rst` -- aside for topic #X

Maybe also naming the directories `topicX_title` for added information.

The main benefit is just organizational. Searching for given topics is faster, and it gives more direct links between images/asides and where they are used.

**Comment by twentylemon** [comment]
> Maybe also naming the directories `topicX_title` for added information.


Was reviewing #266 and went looking for previous discussion on computation complexity. I vaguely remembered it was talked about, but don't know where. Opening the source code was basically useless, I have no idea which topic number it was.

**Comment by jameshughes89** [comment]
> > Maybe also naming the directories `topicX_title` for added information.
> 
> Was reviewing #266 and went looking for previous discussion on computation complexity. I vaguely remembered it was talked about, but don't know where. Opening the source code was basically useless, I have no idea which topic number it was.

It's in Topic9 (#92 #94 #95 #96 #97). Also, I see your point:
> Searching for given topics is faster
