### ISSUE TITLE
💄 🔭 Use `literalinclude` rst directive

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#479]
### What 
Looks like, instead of copy/pasting code into an rst file, [you can reference an actual chunk of code from another file](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude), like maybe the actual `.java` file. **However**, it's not clear how great this would be with java vs python.

This may seem more good than it is at this stage as there are some deliberate differences between the code in the rst files and the actual code. Either way, this is something for futur consideration.

### Why
I can see this helping with consistency. 

### Where
Everywhere. Including cs101 too.

**Comment by jameshughes89** [comment]
This has been addressed through the various updated to the course content for the Winter 2023 year. As of now, however, this is not fully resolved.

It is expected if all the code is cleaned up in the Winter 2023 semester, this issue can be closed.

**Comment by jameshughes89** [comment]
[Upon some reading](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude), the way this is being done can be improved:
1. `:lineno-match:` will start the line numbers matching the line numbers in the file. Currently it's hardcoded, which is a problem (see 2). 
2. `:begin-at:`, `:begin-after:`, and `:end-before:` to not have to hard code the line numbers. Currently the problem is, if any of the code in the actual java files moves around, all the literal-includes break since they will then reference the wrong lines. Unfortunately, the docs makes it seem like there isn't a nice way to say end at a close brace or something.

**Comment by jameshughes89** [comment]
![image](https://user-images.githubusercontent.com/1328048/212204725-8776358a-73aa-4c4f-b0d0-b9f1f15157e2.png)

![image](https://user-images.githubusercontent.com/1328048/212204758-332e0bcd-ce1b-40cb-9fff-548619e4be85.png)

![image](https://user-images.githubusercontent.com/1328048/212204782-0cf0fe2b-16f8-459f-a331-930daf8eb6ef.png)

![image](https://user-images.githubusercontent.com/1328048/212204874-ae512fb5-a5ed-4d27-81d7-6659b7b644f2.png)

**Comment by jameshughes89** [comment]
> Unfortunately, the docs makes it seem like there isn't a nice way to say end at a close brace or something.

Nvm

> If start-after is given as a string option, only lines that follow the first line containing that string are included. If end-before is given as a string option, only lines that precede the first lines containing that string are included. 

Though, there is difficulty with starting at a java doc comment `/**` if there are several in the file.

**Comment by jameshughes89** [comment]
When discussing offline, the simplest solution is to just add some simple comments as tags for the starting/ending at. 

[This is described in the docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude) but the original worry was that there would be weird tags in the source code. Though, after 2s of discussion, this was determined to be clearly moot; the value of not having to update every literal include with future changes greatly outweighs the immense suffering of having a comment or two in the source.

**Comment by twentylemon** [comment]
> When discussing offline, the simplest solution is to just add some simple comments as tags for the starting/ending at.

Just for clarity:

```java
// incl-topicname-part-start
/** ... code ... */
// incl-topicname-part-end
```

Then you can `:start-at: incl-topicname-part-start` and `:end-at: incl-topicname-part-end`.

**Comment by jameshughes89** [comment]
As of now, i believe `literalinclude` has been used everywhere it can, but the outstanding issue is to use tags to eliminate the use of explicit hard coded line numbers.
