### ISSUE TITLE
Topic 16 

### ISSUE THREAD

**Issue by Braydenleblanc29** [jameshughes89/cs102#567]
:new: :bomb: :mortar_board: :memo: :robot: :lipstick: :bug: :telescope: :art: Add relevant emojis to title. [See style guide.](https://github.com/jameshughes89/cs102/blob/main/CONTRIBUTING.md#style-guidelines).

### What 
"For example, here is an example of using an iterator to iterate over an arbitrary iterable thing of type T"

### Why
using "for example" twice in same sentence 

### Where
topic 16 -- Iterator Interface

### How
 replace sentence with "Here is an example of using an iterator to iterate over an arbitrary iterable thing of type T"

**Comment by jameshughes89** [comment]
@Braydenleblanc29 Make a PR and we'll get it merged.

**Comment by jameshughes89** [comment]
Closed by #568
