### ISSUE TITLE
Assignment 3 Change Method Name

### ISSUE THREAD

**Issue by consoleLog7** [jameshughes89/cs102#573]
### What 
In Assignment 3, Part 3, Implementing the class, "T front()" should be "T first()"

### Why
In the Queue interface provided for the assignment, T first() is the method required as per the interface, but the assignment description asks for T front()

### Where
In Assignment 3 description for implementing LinkedPriorityQueue, T front() is the requested method

### How
This can be fixed by changing T front() to T first()

### Additional Notes
This was discovered during automatic method implementation to match the interface in Intelij

**Comment by jameshughes89** [comment]
Good catch. @consoleLog7, submit the PR to fix this.
