### ISSUE TITLE
Make "playing" code actual `.java` files to download

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#77]
As of now I just dump some code to play with asses on the website. Should probably make these actual downloadable files to play with.

**Comment by twentylemon** [comment]
Related to #46

**Comment by jameshughes89** [comment]
RE #75, @twentylemon suggests

> Again semi related to #46, but you could include these as actual main classes in the repo; like, actual java source files.

Which I think is a great idea.

**Comment by jameshughes89** [comment]
I finished this last year, just never closed issue
