### ISSUE TITLE
:memo: change good first issue label name

### ISSUE THREAD

**Issue by twentylemon** [jameshughes89/cs102#89]
### Related Issues or PRs
#85 

### What 
👶 might not be the best for _good first issue_. 

### Why
Top of the issues page sometimes writes:

> Now, GitHub will help potential first-time contributors discover issues labeled with good first issue --- baby 👶

"good first issue -- baby" kinda sounds like we're saying "baby" in the derogatory manner.

### Where
Issue template, PR template, repository labels.

### How
Other emoji options I can thing of, in a rough preference order of mine:
* 👌 ok_hand
* ❤️ heart
* 😎 sunglasses
* ☀️ sunny
* 🆗   ok 
* 😍 heart_eyes
* 🙌 raised_hands
* 🥇  1st_place_medal

**Comment by jameshughes89** [comment]
:medal_sports:  medal_sports
