### ISSUE TITLE
:robot: Change math tool from mathjax to imgmath

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs102#93]
### Related Issues or PRs
#92 

### What 
imgmath was changed out for mathjax due to LaTeX dependencies, however @twentylemon noticed that [mathjax renders client side](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax). 

### Why
This may not be a problem, but to eliminate potential issues, this could be addressed. 

### Where
src/site/conf.py, however it is [recommended to set `imgmath_latex` using an argument to the sphinx-build](https://www.sphinx-doc.org/en/master/usage/extensions/math.html#confval-imgmath_latex).

### How
Will need to figure out the LaTeX dependency

**Comment by twentylemon** [comment]
> The command name with which to invoke LaTeX. The default is 'latex'; you may need to set this to a full path if latex is not in the executable search path.

Think it's fine to install latex and assume it's on the path. Portability is a concern, especially since [gradle is the one invoking sphinx](https://github.com/jameshughes89/cs102/blob/main/build.gradle#L31).

Note that we'll also have to install latex in the github actions.

**Comment by jameshughes89** [comment]
Seems too complex and not important enough to matter
